image: ubuntu:latest

variables:
  NPROC: 8

stages:
  - build
  - test
  - package

x64.l.build:
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq  build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev
      libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm zip
    - scons -j{{NPROC}} platform=linuxbsd bits=64 target=release_debug tests=yes
  artifacts:
    paths:
      - bin/

x64.l.test:
  stage: test
  script:
    - ./bin/godot.linuxbsd.opt.tools.64  --test

x64.l.package:
  stage: package
  script:
    - scons -j{{NPROC}} platform=linuxbsd target=release bits=64
    - zip bin/package.zip bin/godot.linuxbsd.tools.64
  artifacts:
    paths:
    - bin/package.zip

